### ISSUE TITLE
API tests fail in jenkins

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#29]
FNASTESTIP=0.0.0.0
Saving key "/usr/local/jenkins/.ssh/test_id_rsa" failed: No such file or directory
/usr/local/jenkins/.ssh/test_id_rsa: No such file or directory
Traceback (most recent call last):
  File "runtest.py", line 71, in <module>
    f = open(keyPath +'.pub', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/jenkins/.ssh/test_id_rsa.pub'
Build step 'Console output (build log) parsing' changed build result to FAILURE
Finished: FAILURE

**Comment by pkgdemon** [comment]
False alarm.  I had my bridge setup improperly.

**Comment by pkgdemon** [comment]
Turns out this is real

Enter an option from 1-12: c

FNASTESTIP=10.231.3.103
Saving key "/usr/local/jenkins/.ssh/test_id_rsa" failed: No such file or directory
/usr/local/jenkins/.ssh/test_id_rsa: No such file or directory
Traceback (most recent call last):
  File "runtest.py", line 71, in <module>
    f = open(keyPath +'.pub', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/jenkins/.ssh/test_id_rsa.pub'
Build step 'Console output (build log) parsing' changed build result to FAILURE
Finished: FAILURE

**Comment by pkgdemon** [comment]
![log parser issue](https://user-images.githubusercontent.com/4109732/32197583-327bde9a-bd9b-11e7-98f0-e8b14dc7eb11.png)

**Comment by pkgdemon** [comment]
https://github.com/iXsystems/ixbuild/commit/820f8f462eb22bf25172edb72537ccfb2275b2ee
