### ISSUE TITLE
Running outside of jenkins not working

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#53]

**Comment by ericbsd** [comment]
What is not working?

**Comment by pkgdemon** [comment]
Without ixautomation.conf:

```
[jmaloney@joe-desktop] ~% sudo ixautomation --run vm-tests freenas
Please add /usr/local/etc/ixautomation.conf
Traceback (most recent call last):
  File "/usr/local/bin/ixautomation", line 90, in <module>
    if systype not in systypelist:
NameError: name 'systype' is not defined
```

**Comment by pkgdemon** [comment]
With ixautomation.conf:

```
[jmaloney@joe-desktop] /usr/local/etc% sudo ixautomation --run vm-tests freenas
Traceback (most recent call last):
  File "/usr/local/bin/ixautomation", line 90, in <module>
    if systype not in systypelist:
NameError: name 'systype' is not defined
```

**Comment by ericbsd** [comment]
The command is:
`sudo ixautomation --run vm-tests --systype freenas`

**Comment by pkgdemon** [comment]
It does work.  Src for tests has to exist at the exact directory specified in /usr/local/etc/ixautomation.conf.  I was also not specifying --systype which generated the errors above.  False alarm.
