### ISSUE TITLE
Firefox closes when webui function runs

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#76]
Currently Firefox closes, and it would appear export display is not working because of the wrong default user shell.  If we can we need to find a way to specify the default shell with python to make this work.

**Comment by pkgdemon** [comment]
[jmaloney@joe-desktop] ~/projects/ixsystems/ixautomation% sudo ixautomation --run webui-tests --systype freenas --ip 10.20.20.92
The directory '/usr/home/jmaloney/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/usr/home/jmaloney/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: unittest-xml-reporting in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.6/site-packages (from unittest-xml-reporting)
Traceback (most recent call last):
  File "runtest.py", line 79, in <module>
    runDriver = webDriver()
  File "/usr/home/jmaloney/projects/freenas/webui/tests/driver.py", line 30, in webDriver
    driver = webdriver.Firefox(capabilities=caps)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 175, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 104, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by pkgdemon** [comment]
Multiple issues here

Need to keep DISPLAY
This requires access controls be disabled with xhost +
We need to make sure DISPLAY variable can be unique on multiple runs.

**Comment by pkgdemon** [comment]
https://github.com/iXsystems/ixautomation/commit/65c1caf81ccbcb7217266d64ed820474223cf496
